try:
    raise NameError
except:
    print("Re-raising the exception")
    raise